apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: dev-env
spec:
  type: NodePort #LoadBalancer
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002  # You can specify any available port here

#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: tomcat-service
#  namespace: dev-env
#spec:
#  type: NodePort
#  selector:
#    app: tomcat
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#      nodePort: 30001  # You can specify any available port here

