apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-dply
  namespace: dev-env
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 907019346004.dkr.ecr.us-east-1.amazonaws.com/mpf:helloworldlatest
        ports:
        - containerPort: 80
        imagePullPolicy: Always